# Generated by Django 2.1.3 on 2018-11-22 22:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 22, 22, 16, 23, 744946, tzinfo=utc)),
        ),
    ]
